version: "3.1"
services:
  my-db:
    platform: linux/amd64 # for apple chip
    image: mariadb:latest
    environment: 
      - MARIADB_ALLOW_EMPTY_ROOT_PASSWORD=true
      - MARIADB_DATABASE=mydb
    ports:
      - 3306:3306
    volumes: 
      # - C:\work\git\docker-examples\docker-compose\data:/var/lib/mysql # for windows
      - /Users/edowon/Desktop/Work/14.online/devops-docker/docker-compose/data:/var/lib/mysql # for macos